services:
  harmon:
    image: heraclitoqsaldanha/harmon-server:latest
    container_name: harmon
    restart: unless-stopped
    working_dir: /app
    networks:
      - webnet
    env_file:
      - .env
    environment:
      - SERVER_ADDR=0.0.0.0
      - SERVER_PORT=6565
      - CONFIG_PATH=/app/config.toml
      - DATABASE_URL=sqlite:///app/data/database.db
    volumes:
      - ./config.toml:/app/config.toml:ro
      - ./icon.png:/app/icon.png:ro
      - harmon:/app/data

volumes:
  harmon:

networks:
  webnet:
    name: webnet
